version: "3.9"

services:
  vcard-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    container_name: vcard-api
    restart: unless-stopped

    env_file:
      - ../.env

    expose:
      - "8000"

    volumes:
      - ../templates:/app/templates
      - ../thumbnails:/app/thumbnails
      - ../qrcodes:/app/qrcodes

    networks:
      - shared_network

    mem_limit: 256m
    cpus: "0.5"

    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  shared_network:
    external: true